  name : Deploy to ECS
  on : 
    push :
      branches : main
  jobs :
    deploy:
      name: CD
      runs-on: ubuntu-latest
      steps:
      - name: Check out latest code
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-southeast-2
      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{secrets.SSH_HOST}}
          USER_NAME: ec2-user
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          sudo docker pull ${{secrets.AWS_ECR_URI}}:latest &&
          sudo docker stop backend-container || true &&
          sudo docker rm backend-container || true &&
          sudo docker run -d --name backend-container -p ${{secrets.PORT}}:${{secrets.PORT}} \
          -e MONGO_URL=${{secrets.MONGO_URL}} \
          -e PORT=${{secrets.PORT}} \
          -e JWT_SECRET=${{secrets.JWT_SECRET}} \
          -e IP=${{secrets.IP}} \
          ${{secrets.AWS_ECR_URI}}:latest '
